name: Test Workflow

on:
  push:
    branches:
      - main

jobs:
  check-biweekly:
    runs-on: ubuntu-latest
    steps:
      - name: Check if today is biweekly from 2024-01-01
        uses: RubenDguez/cron-biweekly@v1.0.0
        with:
          reference-date: "2024-01-01"
        id: check1

      - name: Check if today is biweekly from 2024-01-08
        uses: RubenDguez/cron-biweekly@v1.0.0
        with:
          reference-date: "2024-01-08"
        id: check2

      - name: Output result
        run: |
          echo "Is today biweekly? ${{ steps.check1.outputs.is-biweekly }}"
          echo "Is today biweekly? ${{ steps.check2.outputs.is-biweekly }}"
